language: python
python:
  - "2.7"
  - "3.6"
before_script:
  - wget https://github.com/samtools/htslib/releases/download/1.3.2/htslib-1.3.2.tar.bz2
  - tar jxvf htslib-1.3.2.tar.bz2 
  - cd htslib-1.3.2 && make && export PATH=$PATH:$PWD && cd ..

script:
  - pip install .


  # test scripts (need to improve)
  - annot_utils gene gene.bed.gz
  - annot_utils exon exon.bed.gz
  - annot_utils junction junction.bed.gz
  - annot_utils coding coding.bed.gz
  - annot_utils boundary boundary.bed.gz

