language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
before_script:
  - wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
  - tar jxvf htslib-1.9.tar.bz2 
  - cd htslib-1.9 && make && export PATH=$PATH:$PWD && cd ..

script:
  - pip install .


  # test scripts (need to improve)
  - annot_utils gene gene.bed.gz
  - annot_utils gene gene_grc.bed.gz --grc
  - annot_utils gene gene_hg38.bed.gz --genome_id hg38
  - annot_utils gene gene_mm10.bed.gz --genome_id mm10
  - annot_utils gene gene_gencode.bed.gz --gene_model gencode
   
  - annot_utils exon exon.bed.gz
  - annot_utils exon exon_grc.bed.gz --grc
  - annot_utils exon exon_hg38.bed.gz --genome_id hg38
  - annot_utils exon exon_mm10.bed.gz --genome_id mm10
  - annot_utils exon exon_gencode.bed.gz --gene_model gencode

  - annot_utils junction junction.bed.gz
  - annot_utils junction junction_grc.bed.gz --grc
  - annot_utils junction junction_hg38.bed.gz --genome_id hg38
  - annot_utils junction junction_mm10.bed.gz --genome_id mm10
  - annot_utils junction junction_gencode.bed.gz --gene_model gencode

  - annot_utils coding coding.bed.gz
  - annot_utils coding coding_grc.bed.gz --grc
  - annot_utils coding coding_hg38.bed.gz --genome_id hg38
  - annot_utils coding coding_mm10.bed.gz --genome_id mm10
  - annot_utils coding coding_gencode.bed.gz --gene_model gencode

  - annot_utils boundary boundary.bed.gz
  - annot_utils boundary boundary_grc.bed.gz --grc
  - annot_utils boundary boundary_hg38.bed.gz --genome_id hg38
  - annot_utils boundary boundary_mm10.bed.gz --genome_id mm10

